version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vpc-api-gateway-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vnkxsum6ds1k"
s3_prefix = "test"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "SSLCheck=\"1\""
profile = "experiments"